services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chatbot:
    build: ./chatbot
    ports:
      - "8010:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./chatbot:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"


  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

#  frontend-next:
#    build: ./frontend-next
#    ports:
#      - "3001:3000"
#    env_file:
#      - .env
#    depends_on:
#      - backend
#    volumes:
#      - ./frontend-next:/app
#      - /app/node_modules
#    stdin_open: true
#    tty: true
  frontend-next:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend-next:/app
#      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Importante para watch en Docker
      - WATCHPACK_POLLING=true # Necesario para algunos entornos




volumes:
  pgdata:
  