services:
  backend:
    build: ./backend
    ports:
      - "8003:8000"
    env_file:
      - .env
    #depends_on:
    #  - host.docker.internal
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

#  frontend-next:
#    build: ./frontend-next
#    ports:
#      - "3001:3000"
#    env_file:
#      - .env
#    depends_on:
#      - backend
#    volumes:
#      - ./frontend-next:/app
#      - /app/node_modules
#    stdin_open: true
#    tty: true
  frontend-next:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend-next:/app
#      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Importante para watch en Docker
      - WATCHPACK_POLLING=true # Necesario para algunos entornos

volumes:
  #embeddings_cache:
  pgdata:
  